In [ ]:
import numpy as np

In [ ]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]]) # 3x3 matrix
print(x.ndim) 
print(x.shape)
print(x.size) 

2
(3, 3)
9


In [ ]:
a = np.array( [20,30,40,50] ) 
b = np.array( [1,2,3,4] ) 
c = a-b 
print(c)

[19 28 37 46]


In [ ]:
x = np.array([1,2,3,4,5])
median = np.median(x)
print(median)
sum = x.sum()
sx = np.sin(x)
cx=np.cos(x)
tan=np.tan(x)
print(sum)
print(sx)
print(cx)
print(tan)

3.0
15
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]
